# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\"\x1c\n\x0eTaskGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"T\n\x12TaskCreateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"7\n\x11TaskCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"1\n\x11TaskErrorResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2u\n\x0bTaskService\x12\x35\n\nCreateTask\x12\x12.TaskCreateRequest\x1a\x13.TaskCreateResponse\x12/\n\x07GetTask\x12\x0f.TaskGetRequest\x1a\x13.TaskCreateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKGETREQUEST']._serialized_start=14
  _globals['_TASKGETREQUEST']._serialized_end=42
  _globals['_TASKCREATERESPONSE']._serialized_start=44
  _globals['_TASKCREATERESPONSE']._serialized_end=128
  _globals['_TASKCREATEREQUEST']._serialized_start=130
  _globals['_TASKCREATEREQUEST']._serialized_end=185
  _globals['_TASKERRORRESPONSE']._serialized_start=187
  _globals['_TASKERRORRESPONSE']._serialized_end=236
  _globals['_TASKSERVICE']._serialized_start=238
  _globals['_TASKSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
